name: Test lint

on:
  workflow_call:
    inputs:
      needs-lint:
        description: Whether lint job is needed
        type: boolean
        required: true

jobs:
  test-lint:
    name: Test lint
    runs-on: ubuntu-latest
    if: ${{ inputs.needs-lint == 'true' }}
    timeout-minutes: 30
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true
          use-yarn-hydrate: true

      - name: Lint
        run: yarn lint

      - name: Verify locales
        run: yarn verify-locales --quiet

      - name: Check circular dependencies
        run: yarn circular-deps:check
